name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Checkout code
        uses: actions/checkout@v3
      - run: goimports -w .
      - run: go mod tidy
      - name: Verify no changes from goimports and go mod tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test ./...